##################################################################################################
# Details service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: menzhen
  labels:
    app: menzhen
    service: menzhen
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: menzhen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menzhen-v1
  labels:
    app: menzhen
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menzhen
      version: v1
  template:
    metadata:
      labels:
        app: menzhen
        version: v1
    spec:
      containers:
      - name: menzhen
        image: lizongshen/menzhen:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
##################################################################################################
# Gateway
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /ping
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: menzhen
spec:
  hosts:
  - menzhen
  http:
  - route:
    - destination:
        host: menzhen
        subset: v1
---